In [1]:
import pandas as pd

In [2]:
data_2014=pd.read_csv("Victims_2014.csv",encoding='ISO-8859-1', sep=';')

In [3]:
print(data_2014.head(10))

  Schluesselzahl der Tat              Straftat  Gemeindeschlüssel  \
0                 ------  Straftaten insgesamt            5334002
1                 ------  Straftaten insgesamt            5334002
2                 ------  Straftaten insgesamt            5334002
3                 ------  Straftaten insgesamt            9761000
4                 ------  Straftaten insgesamt            9761000
5                 ------  Straftaten insgesamt            9761000
6                 ------  Straftaten insgesamt            5378004
7                 ------  Straftaten insgesamt            5378004
8                 ------  Straftaten insgesamt            5378004
9                 ------  Straftaten insgesamt           11000000

               Stadt Fallstatus  Opfer insgesamt - Anzahl  \
0             Aachen      voll.                      4033
1             Aachen      vers.                       327
2             Aachen      insg.                      4360
3           Augsburg      voll.                      4599
4           Augsburg      vers.                       544
5           Augsburg      insg.                      5143
6  Bergisch Gladbach      voll.                       986
7  Bergisch Gladbach      vers.                        68
8  Bergisch Gladbach      insg.                      1054
9             Berlin      voll.                     70048

   Opfer insgesamt männlich- Anzahl  Opfer insgesamt weiblich- Anzahl  \
0                              2377                              1656
1                               206                               121
2                              2583                              1777
3                              2940                              1659
4                               410                               134
5                              3350                              1793
6                               510                               476
7                                44                                24
8                               554                               500
9                             42392                             27656

   Kinder bis unter 6 Jahre - Anzahl  \
0                                 15
1                                  3
2                                 18
3                                 30
4                                  3
5                                 33
6                                  8
7                                  0
8                                  8
9                                774

   Kinder bis unter 6 Jahre männlich- Anzahl  ...  \
0                                          6  ...
1                                          0  ...
2                                          6  ...
3                                         21  ...
4                                          1  ...
5                                         22  ...
6                                          3  ...
7                                          0  ...
8                                          3  ...
9                                        408  ...

   Erwachsene 40 bis unter 50 Jahre - weiblich  \
0                                          236
1                                           16
2                                          252
3                                          244
4                                           19
5                                          263
6                                           76
7                                            1
8                                           77
9                                         4449

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50
5                               406
6                                99
7                                12
8                               111
9                              6934

   Erwachsene 50 bis unter 60 Jahre - männlich  \
0                                          234
1                                           21
2                                          255
3                                          249
4                                           38
5                                          287
6                                           51
7                                            4
8                                           55
9                                         4481

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12
5                                          119
6                                           48
7                                            8
8                                           56
9                                         2453

   Erwachsene 60 Jahre und aelter  Erwachsene 60 Jahre und aelter - männlich  \
0                             236                                        132
1                              26                                         10
2                             262                                        142
3                             198                                         94
4                              13                                          7
5                             211                                        101
6                              61                                         31
7                               9                                          5
8                              70                                         36
9                            4126                                       2240

   Erwachsene 60 Jahre und aelter - weiblich  Erwachsene ab 21 Jahre  \
0                                        104                    3191
1                                         16                     256
2                                        120                    3447
3                                        104                    3513
4                                          6                     455
5                                        110                    3968
6                                         30                     767
7                                          4                      49
8                                         34                     816
9                                       1886                   56125

   Erwachsene ab 21 Jahre - männlich  Erwachsene ab 21 Jahre - weiblich
0                               1888                               1303
1                                163                                 93
2                               2051                               1396
3                               2275                               1238
4                                343                                112
5                               2618                               1350
6                                398                                369
7                                 29                                 20
8                                427                                389
9                              34320                              21805

[10 rows x 68 columns]

In [6]:
data_2014 = data_2014.rename(columns={'Schluesselzahl der Tat': 'Schluessel', 'Gemeindeschlüssel': 'Gemeindeschluessel'})
print(data_2014.head())

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

   Opfer insgesamt - Anzahl  Opfer insgesamt männlich- Anzahl  \
0                      4033                              2377
1                       327                               206
2                      4360                              2583
3                      4599                              2940
4                       544                               410

   Opfer insgesamt weiblich- Anzahl  Kinder bis unter 6 Jahre - Anzahl  \
0                              1656                                 15
1                               121                                  3
2                              1777                                 18
3                              1659                                 30
4                               134                                  3

   Kinder bis unter 6 Jahre männlich- Anzahl  ...  \
0                                          6  ...
1                                          0  ...
2                                          6  ...
3                                         21  ...
4                                          1  ...

   Erwachsene 40 bis unter 50 Jahre - weiblich  \
0                                          236
1                                           16
2                                          252
3                                          244
4                                           19

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50

   Erwachsene 50 bis unter 60 Jahre - männlich  \
0                                          234
1                                           21
2                                          255
3                                          249
4                                           38

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12

   Erwachsene 60 Jahre und aelter  Erwachsene 60 Jahre und aelter - männlich  \
0                             236                                        132
1                              26                                         10
2                             262                                        142
3                             198                                         94
4                              13                                          7

   Erwachsene 60 Jahre und aelter - weiblich  Erwachsene ab 21 Jahre  \
0                                        104                    3191
1                                         16                     256
2                                        120                    3447
3                                        104                    3513
4                                          6                     455

   Erwachsene ab 21 Jahre - männlich  Erwachsene ab 21 Jahre - weiblich
0                               1888                               1303
1                                163                                 93
2                               2051                               1396
3                               2275                               1238
4                                343                                112

[5 rows x 68 columns]

In [13]:
data_2014 = data_2014.rename(columns={'Opfer insgesamt - Anzahl': 'Oper insgesamt', 'Opfer insgesamt männlich- Anzahl': 'Opfer männlich', "Opfer insgesamt weiblich- Anzahl":"Opfer weiblich","Kinder bis unter 6 Jahre - Anzahl":"Opfer - Kinder bis unter 6 Jahre - insgesamt","Kinder bis unter 6 Jahre männlich- Anzahl":"Opfer - Kinder bis unter 6 Jahre - männlich","Kinder bis unter 6 Jahre weiblich - Anzahl":"Opfer - Kinder bis unter 6 Jahre - weiblich","Kinder bis unter 14 Jahre insgesamt":"Opfer Kinder bis 14 Jahre- insgesamt","Kinder bis unter 14 Jahre insgesamt männlich":"Opfer Kinder bis 14 Jahre- männlich","Kinder bis unter 14 Jahre insgesamt weiblich":"Opfer Kinder bis 14 Jahre- weiblich","Jugendliche 14 bis unter 18 Jahre insgesamt":"Opfer Jugendliche 14 bis unter 18 Jahre - insgesamt","Jugendliche 14 bis unter 18 Jahre insgesamt - männlich":"Opfer Jugendliche 14 bis unter 18 Jahre - männlich","Jugendliche 14 bis unter 18 Jahre insgesamt - weiblich":"Opfer Jugendliche 14 bis unter 18 Jahre - weiblich","Heranwachsende 18 bis unter 21 Jahre - Anzahl":"Opfer - Heranwachsende 18 bis unter 21 Jahre - insgesamt","Heranwachsende 18 bis unter 21 Jahre männlich - Anzahl":"Opfer - Heranwachsende 18 bis unter 21 Jahre - männlich","Heranwachsende 18 bis unter 21 Jahre weiblich - Anzahl":"Opfer - Heranwachsende 18 bis unter 21 Jahre - weiblich","Erwachsene 60 Jahre und aelter":"Opfer - Erwachsene 60 Jahre und aelter - insgesamt","Erwachsene 60 Jahre und aelter - männlich":"Opfer - Erwachsene 60 Jahre und aelter - männlich","Erwachsene 60 Jahre und aelter - weiblich":"Opfer - Erwachsene 60 Jahre und aelter - weiblich","Erwachsene ab 21 Jahre":"Opfer Erwachsene - insgesamt","Erwachsene ab 21 Jahre - männlich":"Opfer Erwachsene - männlich","Erwachsene ab 21 Jahre - weiblich":"Opfer Erwachsene - weiblich"})

In [16]:
print(len(data_2014.columns))
print(data_2014.head())

68
  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

   Oper insgesamt  Opfer männlich  Opfer weiblich  \
0            4033            2377            1656
1             327             206             121
2            4360            2583            1777
3            4599            2940            1659
4             544             410             134

   Opfer - Kinder bis unter 6 Jahre - insgesamt  \
0                                            15
1                                             3
2                                            18
3                                            30
4                                             3

   Opfer - Kinder bis unter 6 Jahre - männlich  ...  \
0                                            6  ...
1                                            0  ...
2                                            6  ...
3                                           21  ...
4                                            1  ...

   Erwachsene 40 bis unter 50 Jahre - weiblich  \
0                                          236
1                                           16
2                                          252
3                                          244
4                                           19

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50

   Erwachsene 50 bis unter 60 Jahre - männlich  \
0                                          234
1                                           21
2                                          255
3                                          249
4                                           38

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12

   Opfer - Erwachsene 60 Jahre und aelter - insgesamt  \
0                                                236
1                                                 26
2                                                262
3                                                198
4                                                 13

   Opfer - Erwachsene 60 Jahre und aelter - männlich  \
0                                                132
1                                                 10
2                                                142
3                                                 94
4                                                  7

   Opfer - Erwachsene 60 Jahre und aelter - weiblich  \
0                                                104
1                                                 16
2                                                120
3                                                104
4                                                  6

   Opfer Erwachsene - insgesamt  Opfer Erwachsene - männlich  \
0                          3191                         1888
1                           256                          163
2                          3447                         2051
3                          3513                         2275
4                           455                          343

   Opfer Erwachsene - weiblich
0                         1303
1                           93
2                         1396
3                         1238
4                          112

[5 rows x 68 columns]

In [20]:
print(data_2014.columns)
data_2014 = data_2014.replace('männlich', 'maennlich')

Index(['Schluessel', 'Straftat', 'Gemeindeschluessel', 'Stadt', 'Fallstatus',
       'Oper insgesamt', 'Opfer männlich', 'Opfer weiblich',
       'Opfer - Kinder bis unter 6 Jahre - insgesamt',
       'Opfer - Kinder bis unter 6 Jahre - männlich',
       'Opfer - Kinder bis unter 6 Jahre - weiblich',
       'Kinder 6 bis unter 8 Jahre Anzahl',
       'Kinder 6 bis unter 8 Jahre männlich - Anzahl',
       'Kinder 6 bis unter 8 Jahre weiblich - Anzahl',
       'Kinder 8 bis unter 10 Jahre - Anzahl',
       'Kinder 8 bis unter 10 Jahre männlich - Anzahl',
       'Kinder 8 bis unter 10 Jahre weiblich - Anzahl',
       'Kinder 10 bis unter 12 Jahre - Anzahl',
       'Kinder 10 bis unter 12 Jahre männlich- Anzahl',
       'Kinder 10 bis unter 12 Jahre weiblich - Anzahl',
       'Kinder 12 bis unter 14 Jahre - Anzahl',
       'Kinder 12 bis unter 14 Jahre männlich - Anzahl',
       'Kinder 12 bis unter 14 Jahre weiblich - Anzahl',
       'Opfer Kinder bis 14 Jahre- insgesamt',
       'Opfer Kinder bis 14 Jahre- männlich',
       'Opfer Kinder bis 14 Jahre- weiblich',
       'Jugendliche 14 bis unter 16 Jahre - Anzahl',
       'Jugendliche 14 bis unter 16 Jahre männlich - Anzahl',
       'Jugendliche 14 bis unter 16 Jahre weiblich - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre männlich - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre weiblich - Anzahl',
       'Opfer Jugendliche 14 bis unter 18 Jahre - insgesamt',
       'Opfer Jugendliche 14 bis unter 18 Jahre - männlich',
       'Opfer Jugendliche 14 bis unter 18 Jahre - weiblich',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - insgesamt',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - männlich',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - weiblich',
       'Opfer insgesamt unter 21 Jahre',
       'Opfer insgesamt unter 21 Jahre - männlich',
       'Opfer insgesamt unter 21 Jahre - weiblich',
       'Erwachsene 21 bis unter 23 Jahre - Anzahl',
       'Erwachsene 21 bis unter 23 Jahre männlich - Anzahl',
       'Erwachsene 21 bis unter 23 Jahre weiblich - Anzahl',
       'Erwachsene 23 bis unter 25 Jahre - Anzahl',
       'Erwachsene 23 bis unter 25 Jahre männlich- Anzahl',
       'Erwachsene 23 bis unter 25 Jahre weiblich - Anzahl',
       'Erwachsene 21 bis unter 25 Jahre',
       'Erwachsene 21 bis unter 25 Jahre - männlich',
       'Erwachsene 21 bis unter 25 Jahre - weiblich',
       'Erwachsene 25 bis unter 30 Jahre',
       'Erwachsene 25 bis unter 30 Jahre - männlich',
       'Erwachsene 25 bis unter 30 Jahre - weiblich',
       'Erwachsene 30 bis unter 40 Jahre',
       'Erwachsene 30 bis unter 40 Jahre - männlich',
       'Erwachsene 30 bis unter 40 Jahre - weiblich',
       'Erwachsene 40 bis unter 50 Jahre',
       'Erwachsene 40 bis unter 50 Jahre - männlich',
       'Erwachsene 40 bis unter 50 Jahre - weiblich',
       'Erwachsene 50 bis unter 60 Jahre',
       'Erwachsene 50 bis unter 60 Jahre - männlich',
       'Erwachsene 50 bis unter 60 Jahre - weiblich',
       'Opfer - Erwachsene 60 Jahre und aelter - insgesamt',
       'Opfer - Erwachsene 60 Jahre und aelter - männlich',
       'Opfer - Erwachsene 60 Jahre und aelter - weiblich',
       'Opfer Erwachsene - insgesamt', 'Opfer Erwachsene - männlich',
       'Opfer Erwachsene - weiblich'],
      dtype='object')

In [23]:
data_2014.columns = data_2014.columns.str.replace('männlich', 'maennlich')

In [25]:
print(data_2014.columns)

Index(['Schluessel', 'Straftat', 'Gemeindeschluessel', 'Stadt', 'Fallstatus',
       'Oper insgesamt', 'Opfer maennlich', 'Opfer weiblich',
       'Opfer - Kinder bis unter 6 Jahre - insgesamt',
       'Opfer - Kinder bis unter 6 Jahre - maennlich',
       'Opfer - Kinder bis unter 6 Jahre - weiblich',
       'Kinder 6 bis unter 8 Jahre Anzahl',
       'Kinder 6 bis unter 8 Jahre maennlich - Anzahl',
       'Kinder 6 bis unter 8 Jahre weiblich - Anzahl',
       'Kinder 8 bis unter 10 Jahre - Anzahl',
       'Kinder 8 bis unter 10 Jahre maennlich - Anzahl',
       'Kinder 8 bis unter 10 Jahre weiblich - Anzahl',
       'Kinder 10 bis unter 12 Jahre - Anzahl',
       'Kinder 10 bis unter 12 Jahre maennlich- Anzahl',
       'Kinder 10 bis unter 12 Jahre weiblich - Anzahl',
       'Kinder 12 bis unter 14 Jahre - Anzahl',
       'Kinder 12 bis unter 14 Jahre maennlich - Anzahl',
       'Kinder 12 bis unter 14 Jahre weiblich - Anzahl',
       'Opfer Kinder bis 14 Jahre- insgesamt',
       'Opfer Kinder bis 14 Jahre- maennlich',
       'Opfer Kinder bis 14 Jahre- weiblich',
       'Jugendliche 14 bis unter 16 Jahre - Anzahl',
       'Jugendliche 14 bis unter 16 Jahre maennlich - Anzahl',
       'Jugendliche 14 bis unter 16 Jahre weiblich - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre maennlich - Anzahl',
       'Jugendliche 16 bis unter 18 Jahre weiblich - Anzahl',
       'Opfer Jugendliche 14 bis unter 18 Jahre - insgesamt',
       'Opfer Jugendliche 14 bis unter 18 Jahre - maennlich',
       'Opfer Jugendliche 14 bis unter 18 Jahre - weiblich',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - insgesamt',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - maennlich',
       'Opfer - Heranwachsende 18 bis unter 21 Jahre - weiblich',
       'Opfer insgesamt unter 21 Jahre',
       'Opfer insgesamt unter 21 Jahre - maennlich',
       'Opfer insgesamt unter 21 Jahre - weiblich',
       'Erwachsene 21 bis unter 23 Jahre - Anzahl',
       'Erwachsene 21 bis unter 23 Jahre maennlich - Anzahl',
       'Erwachsene 21 bis unter 23 Jahre weiblich - Anzahl',
       'Erwachsene 23 bis unter 25 Jahre - Anzahl',
       'Erwachsene 23 bis unter 25 Jahre maennlich- Anzahl',
       'Erwachsene 23 bis unter 25 Jahre weiblich - Anzahl',
       'Erwachsene 21 bis unter 25 Jahre',
       'Erwachsene 21 bis unter 25 Jahre - maennlich',
       'Erwachsene 21 bis unter 25 Jahre - weiblich',
       'Erwachsene 25 bis unter 30 Jahre',
       'Erwachsene 25 bis unter 30 Jahre - maennlich',
       'Erwachsene 25 bis unter 30 Jahre - weiblich',
       'Erwachsene 30 bis unter 40 Jahre',
       'Erwachsene 30 bis unter 40 Jahre - maennlich',
       'Erwachsene 30 bis unter 40 Jahre - weiblich',
       'Erwachsene 40 bis unter 50 Jahre',
       'Erwachsene 40 bis unter 50 Jahre - maennlich',
       'Erwachsene 40 bis unter 50 Jahre - weiblich',
       'Erwachsene 50 bis unter 60 Jahre',
       'Erwachsene 50 bis unter 60 Jahre - maennlich',
       'Erwachsene 50 bis unter 60 Jahre - weiblich',
       'Opfer - Erwachsene 60 Jahre und aelter - insgesamt',
       'Opfer - Erwachsene 60 Jahre und aelter - maennlich',
       'Opfer - Erwachsene 60 Jahre und aelter - weiblich',
       'Opfer Erwachsene - insgesamt', 'Opfer Erwachsene - maennlich',
       'Opfer Erwachsene - weiblich'],
      dtype='object')

In [30]:
data_2014["Jahr"]=2014
print(data_2014.head())

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

   Oper insgesamt  Opfer maennlich  Opfer weiblich  \
0            4033             2377            1656
1             327              206             121
2            4360             2583            1777
3            4599             2940            1659
4             544              410             134

   Opfer - Kinder bis unter 6 Jahre - insgesamt  \
0                                            15
1                                             3
2                                            18
3                                            30
4                                             3

   Opfer - Kinder bis unter 6 Jahre - maennlich  ...  \
0                                             6  ...
1                                             0  ...
2                                             6  ...
3                                            21  ...
4                                             1  ...

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50

   Erwachsene 50 bis unter 60 Jahre - maennlich  \
0                                           234
1                                            21
2                                           255
3                                           249
4                                            38

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12

   Opfer - Erwachsene 60 Jahre und aelter - insgesamt  \
0                                                236
1                                                 26
2                                                262
3                                                198
4                                                 13

   Opfer - Erwachsene 60 Jahre und aelter - maennlich  \
0                                                132
1                                                 10
2                                                142
3                                                 94
4                                                  7

   Opfer - Erwachsene 60 Jahre und aelter - weiblich  \
0                                                104
1                                                 16
2                                                120
3                                                104
4                                                  6

   Opfer Erwachsene - insgesamt  Opfer Erwachsene - maennlich  \
0                          3191                          1888
1                           256                           163
2                          3447                          2051
3                          3513                          2275
4                           455                           343

   Opfer Erwachsene - weiblich  Jahr
0                         1303  2014
1                           93  2014
2                         1396  2014
3                         1238  2014
4                          112  2014

[5 rows x 69 columns]

In [34]:
#create a new column 
data_2014["Opfer Kinder 6 bis unter 14 Jahre - insgesamt"]=(
    data_2014["Kinder 6 bis unter 8 Jahre Anzahl"] +
    data_2014["Kinder 8 bis unter 10 Jahre - Anzahl"] +
    data_2014["Kinder 10 bis unter 12 Jahre - Anzahl"] +
    data_2014["Kinder 12 bis unter 14 Jahre - Anzahl"])

In [35]:
print(data_2014["Opfer Kinder 6 bis unter 14 Jahre - insgesamt"])

0       117
1        13
2       130
3       227
4        15
       ...
3415      0
3416      0
3417      0
3418      0
3419      0
Name: Opfer Kinder 6 bis unter 14 Jahre - insgesamt, Length: 3420, dtype: int64

In [36]:
data_2014["Opfer Kinder 6  bis unter 14 Jahre - maennlich"]=(
    data_2014["Kinder 6 bis unter 8 Jahre maennlich - Anzahl"] +
    data_2014["Kinder 8 bis unter 10 Jahre maennlich - Anzahl"] +
    data_2014["Kinder 10 bis unter 12 Jahre maennlich- Anzahl"] +
    data_2014["Kinder 12 bis unter 14 Jahre maennlich - Anzahl"])

In [37]:
print(data_2014["Opfer Kinder 6  bis unter 14 Jahre - maennlich"])

0        72
1         6
2        78
3       117
4        12
       ...
3415      0
3416      0
3417      0
3418      0
3419      0
Name: Opfer Kinder 6  bis unter 14 Jahre - maennlich, Length: 3420, dtype: int64

In [38]:
data_2014["Opfer Kinder 6  bis unter 14 Jahre - weiblich"]=(
    data_2014["Kinder 6 bis unter 8 Jahre weiblich - Anzahl"] +
    data_2014["Kinder 8 bis unter 10 Jahre weiblich - Anzahl"] +
    data_2014["Kinder 10 bis unter 12 Jahre weiblich - Anzahl"] +
    data_2014["Kinder 12 bis unter 14 Jahre weiblich - Anzahl"])

In [39]:
print(data_2014["Opfer Kinder 6  bis unter 14 Jahre - weiblich"])

0        45
1         7
2        52
3       110
4         3
       ...
3415      0
3416      0
3417      0
3418      0
3419      0
Name: Opfer Kinder 6  bis unter 14 Jahre - weiblich, Length: 3420, dtype: int64

In [43]:
data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - insgesamt"]=(
    data_2014["Erwachsene 21 bis unter 25 Jahre"] +
    data_2014["Erwachsene 25 bis unter 30 Jahre"] +
    data_2014["Erwachsene 30 bis unter 40 Jahre"] +
    data_2014["Erwachsene 40 bis unter 50 Jahre"] +
    data_2014["Erwachsene 50 bis unter 60 Jahre"] )

print(data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - insgesamt"])

0       2955
1        230
2       3185
3       3315
4        442
        ...
3415       4
3416       5
3417       1
3418       1
3419       2
Name: Opfer Erwachsene 21 bis unter 60 Jahre - insgesamt, Length: 3420, dtype: int64

In [44]:
data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - maennlich"]=(
    data_2014["Erwachsene 21 bis unter 25 Jahre - maennlich"] +
    data_2014["Erwachsene 25 bis unter 30 Jahre - maennlich"] +
    data_2014["Erwachsene 30 bis unter 40 Jahre - maennlich"] +
    data_2014["Erwachsene 40 bis unter 50 Jahre - maennlich"] +
    data_2014["Erwachsene 50 bis unter 60 Jahre - maennlich"] )

print(data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - maennlich"])

0       1756
1        153
2       1909
3       2181
4        336
        ...
3415       4
3416       4
3417       0
3418       1
3419       1
Name: Opfer Erwachsene 21 bis unter 60 Jahre - maennlich, Length: 3420, dtype: int64

In [46]:
data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - weiblich"]=(
    data_2014["Erwachsene 21 bis unter 25 Jahre - weiblich"] +
    data_2014["Erwachsene 25 bis unter 30 Jahre - weiblich"] +
    data_2014["Erwachsene 30 bis unter 40 Jahre - weiblich"] +
    data_2014["Erwachsene 40 bis unter 50 Jahre - weiblich"] +
    data_2014["Erwachsene 50 bis unter 60 Jahre - weiblich"] )

print(data_2014["Opfer Erwachsene 21 bis unter 60 Jahre - weiblich"])

0       1199
1         77
2       1276
3       1134
4        106
        ...
3415       0
3416       1
3417       1
3418       0
3419       1
Name: Opfer Erwachsene 21 bis unter 60 Jahre - weiblich, Length: 3420, dtype: int64

In [47]:
data_2014.to_csv("data_2024.csv",index=False)

In [48]:
print(data_2014.head())

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

   Oper insgesamt  Opfer maennlich  Opfer weiblich  \
0            4033             2377            1656
1             327              206             121
2            4360             2583            1777
3            4599             2940            1659
4             544              410             134

   Opfer - Kinder bis unter 6 Jahre - insgesamt  \
0                                            15
1                                             3
2                                            18
3                                            30
4                                             3

   Opfer - Kinder bis unter 6 Jahre - maennlich  ...  \
0                                             6  ...
1                                             0  ...
2                                             6  ...
3                                            21  ...
4                                             1  ...

   Opfer Erwachsene - insgesamt  Opfer Erwachsene - maennlich  \
0                          3191                          1888
1                           256                           163
2                          3447                          2051
3                          3513                          2275
4                           455                           343

   Opfer Erwachsene - weiblich  Jahr  \
0                         1303  2014
1                           93  2014
2                         1396  2014
3                         1238  2014
4                          112  2014

   Opfer Kinder 6 bis unter 14 Jahre - insgesamt  \
0                                            117
1                                             13
2                                            130
3                                            227
4                                             15

   Opfer Kinder 6  bis unter 14 Jahre - maennlich  \
0                                              72
1                                               6
2                                              78
3                                             117
4                                              12

   Opfer Kinder 6  bis unter 14 Jahre - weiblich  \
0                                             45
1                                              7
2                                             52
3                                            110
4                                              3

   Opfer Erwachsene 21 bis unter 60 Jahre - insgesamt  \
0                                               2955
1                                                230
2                                               3185
3                                               3315
4                                                442

   Opfer Erwachsene 21 bis unter 60 Jahre - maennlich  \
0                                               1756
1                                                153
2                                               1909
3                                               2181
4                                                336

   Opfer Erwachsene 21 bis unter 60 Jahre - weiblich
0                                               1199
1                                                 77
2                                               1276
3                                               1134
4                                                106

[5 rows x 75 columns]

In [49]:
data_2014.drop(columns=["Kinder 6 bis unter 8 Jahre Anzahl","Kinder 6 bis unter 8 Jahre maennlich - Anzahl","Kinder 6 bis unter 8 Jahre weiblich - Anzahl","Kinder 8 bis unter 10 Jahre - Anzahl","Kinder 8 bis unter 10 Jahre maennlich - Anzahl","Kinder 8 bis unter 10 Jahre weiblich - Anzahl","Kinder 10 bis unter 12 Jahre - Anzahl","Kinder 10 bis unter 12 Jahre maennlich- Anzahl","Kinder 10 bis unter 12 Jahre weiblich - Anzahl","Kinder 12 bis unter 14 Jahre - Anzahl","Kinder 12 bis unter 14 Jahre maennlich - Anzahl","Kinder 12 bis unter 14 Jahre weiblich - Anzahl","Jugendliche 14 bis unter 16 Jahre - Anzahl","Jugendliche 14 bis unter 16 Jahre maennlich - Anzahl","Jugendliche 14 bis unter 16 Jahre weiblich - Anzahl","Jugendliche 16 bis unter 18 Jahre - Anzahl","Jugendliche 16 bis unter 18 Jahre maennlich - Anzahl","Jugendliche 16 bis unter 18 Jahre weiblich - Anzahl","Opfer insgesamt unter 21 Jahre","Opfer insgesamt unter 21 Jahre - maennlich","Opfer insgesamt unter 21 Jahre - weiblich","Erwachsene 23 bis unter 25 Jahre - Anzahl","Erwachsene 23 bis unter 25 Jahre maennlich- Anzahl","Erwachsene 23 bis unter 25 Jahre weiblich - Anzahl","Erwachsene 23 bis unter 25 Jahre weiblich - Anzahl","Erwachsene 21 bis unter 25 Jahre","Erwachsene 21 bis unter 25 Jahre - maennlich","Erwachsene 21 bis unter 25 Jahre - weiblich","Erwachsene 25 bis unter 30 Jahre","Erwachsene 25 bis unter 30 Jahre - maennlich","Erwachsene 25 bis unter 30 Jahre - weiblich","Erwachsene 30 bis unter 40 Jahre","Erwachsene 30 bis unter 40 Jahre - maennlich","Erwachsene 30 bis unter 40 Jahre - weiblich","Erwachsene 40 bis unter 50 Jahre","Erwachsene 40 bis unter 50 Jahre - maennlich","Erwachsene 40 bis unter 50 Jahre - weiblich","Erwachsene 50 bis unter 60 Jahre","Erwachsene 50 bis unter 60 Jahre - maennlich","Erwachsene 50 bis unter 60 Jahre - weiblich","Erwachsene 21 bis unter 23 Jahre - Anzahl","Erwachsene 21 bis unter 23 Jahre maennlich - Anzahl","Erwachsene 21 bis unter 23 Jahre weiblich - Anzahl"], inplace=True)

In [53]:
data_2014.to_csv("data_2024.csv",index=False)

In [50]:
print(len(data_2014.columns))

33

In [54]:
new_column_order = [
    'Schluessel',
    'Straftat',
    'Gemeindeschluessel',
    'Stadt',
    'Fallstatus',
    'Oper insgesamt',
    'Opfer maennlich',
    'Opfer weiblich',
    'Opfer - Kinder bis unter 6 Jahre - insgesamt',
    'Opfer - Kinder bis unter 6 Jahre - maennlich',
    'Opfer - Kinder bis unter 6 Jahre - weiblich',
    'Opfer Kinder 6 bis unter 14 Jahre - insgesamt',
    'Opfer Kinder 6  bis unter 14 Jahre - maennlich',
    'Opfer Kinder 6  bis unter 14 Jahre - weiblich',
    'Opfer Kinder bis 14 Jahre- insgesamt',
    'Opfer Kinder bis 14 Jahre- maennlich',
    'Opfer Kinder bis 14 Jahre- weiblich',
    'Opfer Jugendliche 14 bis unter 18 Jahre - insgesamt',
    'Opfer Jugendliche 14 bis unter 18 Jahre - maennlich',
    'Opfer Jugendliche 14 bis unter 18 Jahre - weiblich',
    'Opfer - Heranwachsende 18 bis unter 21 Jahre - insgesamt',
    'Opfer - Heranwachsende 18 bis unter 21 Jahre - maennlich',
    'Opfer - Heranwachsende 18 bis unter 21 Jahre - weiblich',
    'Opfer Erwachsene 21 bis unter 60 Jahre - insgesamt',
    'Opfer Erwachsene 21 bis unter 60 Jahre - maennlich',
    'Opfer Erwachsene 21 bis unter 60 Jahre - weiblich',
    'Opfer - Erwachsene 60 Jahre und aelter - insgesamt',
    'Opfer - Erwachsene 60 Jahre und aelter - maennlich',
    'Opfer - Erwachsene 60 Jahre und aelter - weiblich',
    'Opfer Erwachsene - insgesamt',
    'Opfer Erwachsene - maennlich',
    'Opfer Erwachsene - weiblich',
    'Jahr'
]

In [55]:
data_2014=data_2014[new_column_order]

In [56]:
data_2014.to_csv("data_2024.csv",index=False)

In [57]:
data_2014.columns = data_2014.columns.str.replace(' ', '_', regex=False)

In [58]:
print(data_2014.columns)

Index(['Schluessel', 'Straftat', 'Gemeindeschluessel', 'Stadt', 'Fallstatus',
       'Oper_insgesamt', 'Opfer_maennlich', 'Opfer_weiblich',
       'Opfer_-_Kinder_bis_unter_6_Jahre_-_insgesamt',
       'Opfer_-_Kinder_bis_unter_6_Jahre_-_maennlich',
       'Opfer_-_Kinder_bis_unter_6_Jahre_-_weiblich',
       'Opfer_Kinder_6_bis_unter_14_Jahre_-_insgesamt',
       'Opfer_Kinder_6__bis_unter_14_Jahre_-_maennlich',
       'Opfer_Kinder_6__bis_unter_14_Jahre_-_weiblich',
       'Opfer_Kinder_bis_14_Jahre-_insgesamt',
       'Opfer_Kinder_bis_14_Jahre-_maennlich',
       'Opfer_Kinder_bis_14_Jahre-_weiblich',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre_-_insgesamt',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre_-_maennlich',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre_-_weiblich',
       'Opfer_-_Heranwachsende_18_bis_unter_21_Jahre_-_insgesamt',
       'Opfer_-_Heranwachsende_18_bis_unter_21_Jahre_-_maennlich',
       'Opfer_-_Heranwachsende_18_bis_unter_21_Jahre_-_weiblich',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre_-_insgesamt',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre_-_maennlich',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre_-_weiblich',
       'Opfer_-_Erwachsene_60_Jahre_und_aelter_-_insgesamt',
       'Opfer_-_Erwachsene_60_Jahre_und_aelter_-_maennlich',
       'Opfer_-_Erwachsene_60_Jahre_und_aelter_-_weiblich',
       'Opfer_Erwachsene_-_insgesamt', 'Opfer_Erwachsene_-_maennlich',
       'Opfer_Erwachsene_-_weiblich', 'Jahr'],
      dtype='object')

In [59]:
data_2014.columns = data_2014.columns.str.replace('-', '', regex=False)

In [60]:
print(data_2014.columns)

Index(['Schluessel', 'Straftat', 'Gemeindeschluessel', 'Stadt', 'Fallstatus',
       'Oper_insgesamt', 'Opfer_maennlich', 'Opfer_weiblich',
       'Opfer__Kinder_bis_unter_6_Jahre__insgesamt',
       'Opfer__Kinder_bis_unter_6_Jahre__maennlich',
       'Opfer__Kinder_bis_unter_6_Jahre__weiblich',
       'Opfer_Kinder_6_bis_unter_14_Jahre__insgesamt',
       'Opfer_Kinder_6__bis_unter_14_Jahre__maennlich',
       'Opfer_Kinder_6__bis_unter_14_Jahre__weiblich',
       'Opfer_Kinder_bis_14_Jahre_insgesamt',
       'Opfer_Kinder_bis_14_Jahre_maennlich',
       'Opfer_Kinder_bis_14_Jahre_weiblich',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre__insgesamt',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre__maennlich',
       'Opfer_Jugendliche_14_bis_unter_18_Jahre__weiblich',
       'Opfer__Heranwachsende_18_bis_unter_21_Jahre__insgesamt',
       'Opfer__Heranwachsende_18_bis_unter_21_Jahre__maennlich',
       'Opfer__Heranwachsende_18_bis_unter_21_Jahre__weiblich',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre__insgesamt',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre__maennlich',
       'Opfer_Erwachsene_21_bis_unter_60_Jahre__weiblich',
       'Opfer__Erwachsene_60_Jahre_und_aelter__insgesamt',
       'Opfer__Erwachsene_60_Jahre_und_aelter__maennlich',
       'Opfer__Erwachsene_60_Jahre_und_aelter__weiblich',
       'Opfer_Erwachsene__insgesamt', 'Opfer_Erwachsene__maennlich',
       'Opfer_Erwachsene__weiblich', 'Jahr'],
      dtype='object')