In [1]:
import pandas as pd

In [2]:
df_2014=pd.read_csv("Opfer_2014.csv",encoding='ISO-8859-1', sep=';')

In [3]:
print(df_2014.head(10))

  Schluesselzahl der Tat              Straftat  Gemeindeschlüssel  \
0                 ------  Straftaten insgesamt            5334002
1                 ------  Straftaten insgesamt            5334002
2                 ------  Straftaten insgesamt            5334002
3                 ------  Straftaten insgesamt            9761000
4                 ------  Straftaten insgesamt            9761000
5                 ------  Straftaten insgesamt            9761000
6                 ------  Straftaten insgesamt            5378004
7                 ------  Straftaten insgesamt            5378004
8                 ------  Straftaten insgesamt            5378004
9                 ------  Straftaten insgesamt           11000000

               Stadt Fallstatus  Opfer insgesamt - Anzahl  \
0             Aachen      voll.                      4033
1             Aachen      vers.                       327
2             Aachen      insg.                      4360
3           Augsburg      voll.                      4599
4           Augsburg      vers.                       544
5           Augsburg      insg.                      5143
6  Bergisch Gladbach      voll.                       986
7  Bergisch Gladbach      vers.                        68
8  Bergisch Gladbach      insg.                      1054
9             Berlin      voll.                     70048

   Opfer insgesamt männlich- Anzahl  Opfer insgesamt weiblich- Anzahl  \
0                              2377                              1656
1                               206                               121
2                              2583                              1777
3                              2940                              1659
4                               410                               134
5                              3350                              1793
6                               510                               476
7                                44                                24
8                               554                               500
9                             42392                             27656

   Kinder bis unter 6 Jahre - Anzahl  \
0                                 15
1                                  3
2                                 18
3                                 30
4                                  3
5                                 33
6                                  8
7                                  0
8                                  8
9                                774

   Kinder bis unter 6 Jahre männlich- Anzahl  ...  \
0                                          6  ...
1                                          0  ...
2                                          6  ...
3                                         21  ...
4                                          1  ...
5                                         22  ...
6                                          3  ...
7                                          0  ...
8                                          3  ...
9                                        408  ...

   Erwachsene 40 bis unter 50 Jahre - weiblich  \
0                                          236
1                                           16
2                                          252
3                                          244
4                                           19
5                                          263
6                                           76
7                                            1
8                                           77
9                                         4449

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50
5                               406
6                                99
7                                12
8                               111
9                              6934

   Erwachsene 50 bis unter 60 Jahre - männlich  \
0                                          234
1                                           21
2                                          255
3                                          249
4                                           38
5                                          287
6                                           51
7                                            4
8                                           55
9                                         4481

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12
5                                          119
6                                           48
7                                            8
8                                           56
9                                         2453

   Erwachsene 60 Jahre und aelter  Erwachsene 60 Jahre und aelter - männlich  \
0                             236                                        132
1                              26                                         10
2                             262                                        142
3                             198                                         94
4                              13                                          7
5                             211                                        101
6                              61                                         31
7                               9                                          5
8                              70                                         36
9                            4126                                       2240

   Erwachsene 60 Jahre und aelter - weiblich  Erwachsene ab 21 Jahre  \
0                                        104                    3191
1                                         16                     256
2                                        120                    3447
3                                        104                    3513
4                                          6                     455
5                                        110                    3968
6                                         30                     767
7                                          4                      49
8                                         34                     816
9                                       1886                   56125

   Erwachsene ab 21 Jahre - männlich  Erwachsene ab 21 Jahre - weiblich
0                               1888                               1303
1                                163                                 93
2                               2051                               1396
3                               2275                               1238
4                                343                                112
5                               2618                               1350
6                                398                                369
7                                 29                                 20
8                                427                                389
9                              34320                              21805

[10 rows x 68 columns]

In [4]:
print(df_2014.head())

  Schluesselzahl der Tat              Straftat  Gemeindeschlüssel     Stadt  \
0                 ------  Straftaten insgesamt            5334002    Aachen
1                 ------  Straftaten insgesamt            5334002    Aachen
2                 ------  Straftaten insgesamt            5334002    Aachen
3                 ------  Straftaten insgesamt            9761000  Augsburg
4                 ------  Straftaten insgesamt            9761000  Augsburg

  Fallstatus  Opfer insgesamt - Anzahl  Opfer insgesamt männlich- Anzahl  \
0      voll.                      4033                              2377
1      vers.                       327                               206
2      insg.                      4360                              2583
3      voll.                      4599                              2940
4      vers.                       544                               410

   Opfer insgesamt weiblich- Anzahl  Kinder bis unter 6 Jahre - Anzahl  \
0                              1656                                 15
1                               121                                  3
2                              1777                                 18
3                              1659                                 30
4                               134                                  3

   Kinder bis unter 6 Jahre männlich- Anzahl  ...  \
0                                          6  ...
1                                          0  ...
2                                          6  ...
3                                         21  ...
4                                          1  ...

   Erwachsene 40 bis unter 50 Jahre - weiblich  \
0                                          236
1                                           16
2                                          252
3                                          244
4                                           19

   Erwachsene 50 bis unter 60 Jahre  \
0                               389
1                                32
2                               421
3                               356
4                                50

   Erwachsene 50 bis unter 60 Jahre - männlich  \
0                                          234
1                                           21
2                                          255
3                                          249
4                                           38

   Erwachsene 50 bis unter 60 Jahre - weiblich  \
0                                          155
1                                           11
2                                          166
3                                          107
4                                           12

   Erwachsene 60 Jahre und aelter  Erwachsene 60 Jahre und aelter - männlich  \
0                             236                                        132
1                              26                                         10
2                             262                                        142
3                             198                                         94
4                              13                                          7

   Erwachsene 60 Jahre und aelter - weiblich  Erwachsene ab 21 Jahre  \
0                                        104                    3191
1                                         16                     256
2                                        120                    3447
3                                        104                    3513
4                                          6                     455

   Erwachsene ab 21 Jahre - männlich  Erwachsene ab 21 Jahre - weiblich
0                               1888                               1303
1                                163                                 93
2                               2051                               1396
3                               2275                               1238
4                                343                                112

[5 rows x 68 columns]

In [5]:
df_2014.columns = df_2014.columns.str.replace(' ', '')

In [6]:
print(df_2014.head(10))

  SchluesselzahlderTat              Straftat  Gemeindeschlüssel  \
0               ------  Straftaten insgesamt            5334002
1               ------  Straftaten insgesamt            5334002
2               ------  Straftaten insgesamt            5334002
3               ------  Straftaten insgesamt            9761000
4               ------  Straftaten insgesamt            9761000
5               ------  Straftaten insgesamt            9761000
6               ------  Straftaten insgesamt            5378004
7               ------  Straftaten insgesamt            5378004
8               ------  Straftaten insgesamt            5378004
9               ------  Straftaten insgesamt           11000000

               Stadt Fallstatus  Opferinsgesamt-Anzahl  \
0             Aachen      voll.                   4033
1             Aachen      vers.                    327
2             Aachen      insg.                   4360
3           Augsburg      voll.                   4599
4           Augsburg      vers.                    544
5           Augsburg      insg.                   5143
6  Bergisch Gladbach      voll.                    986
7  Bergisch Gladbach      vers.                     68
8  Bergisch Gladbach      insg.                   1054
9             Berlin      voll.                  70048

   Opferinsgesamtmännlich-Anzahl  Opferinsgesamtweiblich-Anzahl  \
0                           2377                           1656
1                            206                            121
2                           2583                           1777
3                           2940                           1659
4                            410                            134
5                           3350                           1793
6                            510                            476
7                             44                             24
8                            554                            500
9                          42392                          27656

   Kinderbisunter6Jahre-Anzahl  Kinderbisunter6Jahremännlich-Anzahl  ...  \
0                           15                                    6  ...
1                            3                                    0  ...
2                           18                                    6  ...
3                           30                                   21  ...
4                            3                                    1  ...
5                           33                                   22  ...
6                            8                                    3  ...
7                            0                                    0  ...
8                            8                                    3  ...
9                          774                                  408  ...

   Erwachsene40bisunter50Jahre-weiblich  Erwachsene50bisunter60Jahre  \
0                                   236                          389
1                                    16                           32
2                                   252                          421
3                                   244                          356
4                                    19                           50
5                                   263                          406
6                                    76                           99
7                                     1                           12
8                                    77                          111
9                                  4449                         6934

   Erwachsene50bisunter60Jahre-männlich  Erwachsene50bisunter60Jahre-weiblich  \
0                                   234                                   155
1                                    21                                    11
2                                   255                                   166
3                                   249                                   107
4                                    38                                    12
5                                   287                                   119
6                                    51                                    48
7                                     4                                     8
8                                    55                                    56
9                                  4481                                  2453

   Erwachsene60Jahreundaelter  Erwachsene60Jahreundaelter-männlich  \
0                         236                                  132
1                          26                                   10
2                         262                                  142
3                         198                                   94
4                          13                                    7
5                         211                                  101
6                          61                                   31
7                           9                                    5
8                          70                                   36
9                        4126                                 2240

   Erwachsene60Jahreundaelter-weiblich  Erwachseneab21Jahre  \
0                                  104                 3191
1                                   16                  256
2                                  120                 3447
3                                  104                 3513
4                                    6                  455
5                                  110                 3968
6                                   30                  767
7                                    4                   49
8                                   34                  816
9                                 1886                56125

   Erwachseneab21Jahre-männlich  Erwachseneab21Jahre-weiblich
0                          1888                          1303
1                           163                            93
2                          2051                          1396
3                          2275                          1238
4                           343                           112
5                          2618                          1350
6                           398                           369
7                            29                            20
8                           427                           389
9                         34320                         21805

[10 rows x 68 columns]

In [7]:
df_2014["Jahr"] = 2014
print(df_2014.head())
print(df_2014["Jahr"])

  SchluesselzahlderTat              Straftat  Gemeindeschlüssel     Stadt  \
0               ------  Straftaten insgesamt            5334002    Aachen
1               ------  Straftaten insgesamt            5334002    Aachen
2               ------  Straftaten insgesamt            5334002    Aachen
3               ------  Straftaten insgesamt            9761000  Augsburg
4               ------  Straftaten insgesamt            9761000  Augsburg

  Fallstatus  Opferinsgesamt-Anzahl  Opferinsgesamtmännlich-Anzahl  \
0      voll.                   4033                           2377
1      vers.                    327                            206
2      insg.                   4360                           2583
3      voll.                   4599                           2940
4      vers.                    544                            410

   Opferinsgesamtweiblich-Anzahl  Kinderbisunter6Jahre-Anzahl  \
0                           1656                           15
1                            121                            3
2                           1777                           18
3                           1659                           30
4                            134                            3

   Kinderbisunter6Jahremännlich-Anzahl  ...  Erwachsene50bisunter60Jahre  \
0                                    6  ...                          389
1                                    0  ...                           32
2                                    6  ...                          421
3                                   21  ...                          356
4                                    1  ...                           50

   Erwachsene50bisunter60Jahre-männlich  Erwachsene50bisunter60Jahre-weiblich  \
0                                   234                                   155
1                                    21                                    11
2                                   255                                   166
3                                   249                                   107
4                                    38                                    12

   Erwachsene60Jahreundaelter  Erwachsene60Jahreundaelter-männlich  \
0                         236                                  132
1                          26                                   10
2                         262                                  142
3                         198                                   94
4                          13                                    7

   Erwachsene60Jahreundaelter-weiblich  Erwachseneab21Jahre  \
0                                  104                 3191
1                                   16                  256
2                                  120                 3447
3                                  104                 3513
4                                    6                  455

   Erwachseneab21Jahre-männlich  Erwachseneab21Jahre-weiblich  Jahr
0                          1888                          1303  2014
1                           163                            93  2014
2                          2051                          1396  2014
3                          2275                          1238  2014
4                           343                           112  2014

[5 rows x 69 columns]
0       2014
1       2014
2       2014
3       2014
4       2014
        ...
3415    2014
3416    2014
3417    2014
3418    2014
3419    2014
Name: Jahr, Length: 3420, dtype: int64

In [21]:
df_2015=pd.read_csv("Opfer_2015.csv",encoding='ISO-8859-1', sep=';')
df_2015.columns = df_2015.columns.str.replace(' ', '')
df_2015["Jahr"] = 2015
print(df_2015.head())
print(df_2015["Jahr"])
df_2015= df_2015.iloc[:, :-1]

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

  Opferinsgesamt-Anzahl Opferinsgesamtmaennlich-Anzahl  \
0                 3,824                          2,289
1                   297                            171
2                 4,121                          2,460
3                 4,405                          2,758
4                   579                            415

  Opferinsgesamtweiblich-Anzahl  Kinderbisunter6Jahre-Anzahl  \
0                         1,535                           23
1                           126                            0
2                         1,661                           23
3                         1,647                           43
4                           164                            6

   Kinderbisunter6Jahremaennlich-Anzahl  ...  \
0                                    12  ...
1                                     0  ...
2                                    12  ...
3                                    26  ...
4                                     3  ...

   Erwachsene50bisunter60Jahre-maennlich  \
0                                    251
1                                     26
2                                    277
3                                    224
4                                     40

   Erwachsene50bisunter60Jahre-weiblich  Erwachsene60Jahreundaelter  \
0                                   119                         248
1                                    12                          35
2                                   131                         283
3                                   113                         181
4                                    21                          30

   Erwachsene60Jahreundaelter-maennlich  Erwachsene60Jahreundaelter-weiblich  \
0                                   130                                  118
1                                    12                                   23
2                                   142                                  141
3                                   101                                   80
4                                    22                                    8

   Erwachseneab21Jahre  Erwachseneab21Jahre-maennlich  \
0                3,007                          1,800
1                  251                            143
2                3,258                          1,943
3                3,504                          2,218
4                  491                            366

  Erwachseneab21Jahre-weiblich  Unnamed:68  Jahr
0                        1,207           0  2015
1                          108           0  2015
2                        1,315           0  2015
3                        1,286           0  2015
4                          125           0  2015

[5 rows x 70 columns]
0        2015
1        2015
2        2015
3        2015
4        2015
         ...
42037    2015
42038    2015
42039    2015
42040    2015
42041    2015
Name: Jahr, Length: 42042, dtype: int64

C:\Users\PC\AppData\Local\Temp\ipykernel_2368\2901262035.py:1: DtypeWarning: Columns (0,7,17,20,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,67) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2015=pd.read_csv("Opfer_2015.csv",encoding='ISO-8859-1', sep=';')

In [9]:
df_2016=pd.read_csv("Opfer_2016.csv",encoding='ISO-8859-1', sep=';')
df_2016.columns = df_2016.columns.str.replace(' ', '')
df_2016["Jahr"] = 2016
print(df_2016.head())
print(df_2016["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel              Stadt  \
0     ------  Straftaten insgesamt             5334002             Aachen
1     ------  Straftaten insgesamt             9761000           Augsburg
2     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
3     ------  Straftaten insgesamt            11000000             Berlin
4     ------  Straftaten insgesamt             5711000          Bielefeld

  Fallstatus Opferinsgesamt-Anzahl Opferinsgesamtmaennlich-Anzahl  \
0      voll.                 4,334                          2,672
1      voll.                 4,601                          2,922
2      voll.                 1,228                            670
3      voll.                71,286                         43,825
4      voll.                 4,245                          2,412

  Opferinsgesamtweiblich-Anzahl  Kinderbisunter6Jahre-Anzahl  \
0                         1,662                           17
1                         1,679                           29
2                           558                            7
3                        27,461                          794
4                         1,833                           29

   Kinderbisunter6Jahremaennlich-Anzahl  ...  Erwachsene50bisunter60Jahre  \
0                                    13  ...                          431
1                                    11  ...                          395
2                                     1  ...                          142
3                                   419  ...                        7,544
4                                    16  ...                          385

   Erwachsene50bisunter60Jahre-maennlich  \
0                                    277
1                                    269
2                                     78
3                                  4,899
4                                    262

   Erwachsene50bisunter60Jahre-weiblich  Erwachsene60Jahreundaelter  \
0                                   154                         274
1                                   126                         209
2                                    64                         108
3                                 2,645                       4,173
4                                   123                         214

   Erwachsene60Jahreundaelter-maennlich  Erwachsene60Jahreundaelter-weiblich  \
0                                   166                                  108
1                                   121                                   88
2                                    58                                   50
3                                 2,331                                1,842
4                                   119                                   95

   Erwachseneab21Jahre Erwachseneab21Jahre-maennlich  \
0                3,472                         2,158
1                3,598                         2,317
2                  983                           534
3               56,912                        35,275
4                3,357                         1,908

   Erwachseneab21Jahre-weiblich  Jahr
0                         1,314  2016
1                         1,281  2016
2                           449  2016
3                        21,637  2016
4                         1,449  2016

[5 rows x 69 columns]
0       2016
1       2016
2       2016
3       2016
4       2016
        ...
3115    2016
3116    2016
3117    2016
3118    2016
3119    2016
Name: Jahr, Length: 3120, dtype: int64

In [10]:
df_2017=pd.read_csv("Opfer_2017.csv",encoding='ISO-8859-1', sep=';')
df_2017.columns = df_2017.columns.str.replace(' ', '')
df_2017["Jahr"] = 2017
print(df_2017.head())
print(df_2017["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel              Stadt  \
0     ------  Straftaten insgesamt             5334002             Aachen
1     ------  Straftaten insgesamt             9761000           Augsburg
2     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
3     ------  Straftaten insgesamt            11000000             Berlin
4     ------  Straftaten insgesamt             5711000          Bielefeld

  Fallstatus Opferinsgesamt-Anzahl Opferinsgesamtmaennlich-Anzahl  \
0      voll.                 4,191                          2,534
1      voll.                 4,475                          2,797
2      voll.                 1,168                            627
3      voll.                71,397                         43,330
4      voll.                 4,113                          2,218

  Opferinsgesamtweiblich-Anzahl  Kinderbisunter6Jahre-Anzahl  \
0                         1,657                           20
1                         1,678                           50
2                           541                           10
3                        28,067                          815
4                         1,895                           39

   Kinderbisunter6Jahremaennlich-Anzahl  ...  Erwachsene50bisunter60Jahre  \
0                                    13  ...                          402
1                                    31  ...                          369
2                                     8  ...                          134
3                                   407  ...                        7,326
4                                    26  ...                          431

   Erwachsene50bisunter60Jahre-maennlich  \
0                                    271
1                                    236
2                                     84
3                                  4,601
4                                    251

   Erwachsene50bisunter60Jahre-weiblich  Erwachsene60Jahreundaelter  \
0                                   131                         230
1                                   133                         216
2                                    50                          73
3                                 2,725                       4,166
4                                   180                         191

   Erwachsene60Jahreundaelter-maennlich  Erwachsene60Jahreundaelter-weiblich  \
0                                   129                                  101
1                                   122                                   94
2                                    41                                   32
3                                 2,242                                1,924
4                                   109                                   82

   Erwachseneab21Jahre Erwachseneab21Jahre-maennlich  \
0                3,344                         2,014
1                3,404                         2,168
2                  884                           468
3               56,389                        34,602
4                3,240                         1,733

   Erwachseneab21Jahre-weiblich  Jahr
0                         1,330  2017
1                         1,236  2017
2                           416  2017
3                        21,787  2017
4                         1,507  2017

[5 rows x 69 columns]
0       2017
1       2017
2       2017
3       2017
4       2017
        ...
3154    2017
3155    2017
3156    2017
3157    2017
3158    2017
Name: Jahr, Length: 3159, dtype: int64

In [11]:
df_2018=pd.read_csv("Opfer_2018.csv",encoding='ISO-8859-1', sep=';')
df_2018.columns = df_2018.columns.str.replace(' ', '')
df_2018["Jahr"] = 2018
print(df_2018.head())
print(df_2018["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel              Stadt  \
0     ------  Straftaten insgesamt             5334002             Aachen
1     ------  Straftaten insgesamt             9761000           Augsburg
2     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
3     ------  Straftaten insgesamt            11000000             Berlin
4     ------  Straftaten insgesamt             5711000          Bielefeld

  Fallstatus Opferinsgesamt-Anzahl Opferinsgesamtmaennlich-Anzahl  \
0      voll.                 4,057                          2,402
1      voll.                 4,769                          3,050
2      voll.                 1,216                            646
3      voll.                74,153                         45,011
4      voll.                 4,219                          2,282

  Opferinsgesamtweiblich-Anzahl  Kinderbisunter6Jahre-Anzahl  \
0                         1,655                           10
1                         1,719                           43
2                           570                            4
3                        29,142                          826
4                         1,937                           32

   Kinderbisunter6Jahremaennlich-Anzahl  ...  Erwachsene50bisunter60Jahre  \
0                                     4  ...                          411
1                                    25  ...                          424
2                                     2  ...                          127
3                                   454  ...                        7,686
4                                    23  ...                          412

   Erwachsene50bisunter60Jahre-maennlich  \
0                                    252
1                                    271
2                                     67
3                                  4,923
4                                    262

   Erwachsene50bisunter60Jahre-weiblich  Erwachsene60Jahreundaelter  \
0                                   159                         242
1                                   153                         243
2                                    60                         108
3                                 2,763                       4,239
4                                   150                         249

   Erwachsene60Jahreundaelter-maennlich  Erwachsene60Jahreundaelter-weiblich  \
0                                   138                                  104
1                                   140                                  103
2                                    58                                   50
3                                 2,332                                1,907
4                                   122                                  127

   Erwachseneab21Jahre Erwachseneab21Jahre-maennlich  \
0                3,265                         1,965
1                3,734                         2,427
2                  926                           473
3               58,876                        36,203
4                3,318                         1,765

   Erwachseneab21Jahre-weiblich  Jahr
0                         1,300  2018
1                         1,307  2018
2                           453  2018
3                        22,673  2018
4                         1,553  2018

[5 rows x 69 columns]
0       2018
1       2018
2       2018
3       2018
4       2018
        ...
3640    2018
3641    2018
3642    2018
3643    2018
3644    2018
Name: Jahr, Length: 3645, dtype: int64

In [12]:
df_2019=pd.read_csv("Opfer_2019.csv",encoding='ISO-8859-1', sep=';')
df_2019.columns = df_2019.columns.str.replace(' ', '')
df_2019["Jahr"] = 2019
print(df_2019.head())
print(df_2019["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

  Operinsgesamt Opfermaennlich Opferweiblich  \
0         3,828          2,252         1,576
1           304            182           122
2         4,132          2,434         1,698
3         4,879          3,198         1,681
4           480            354           126

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                    23                                    13
1                                     1                                     0
2                                    24                                    13
3                                    26                                    17
4                                     4                                     2

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                       2,809
1  ...                                         234
2  ...                                       3,043
3  ...                                       3,555
4  ...                                         368

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                      1,645
1                                        138
2                                      1,783
3                                      2,388
4                                        277

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                     1,164
1                                        96
2                                     1,260
3                                     1,167
4                                        91

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                        276
1                                         15
2                                        291
3                                        243
4                                         15

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                        175
1                                          7
2                                        182
3                                        149
4                                          9

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                       101                     3,085
1                                         8                       249
2                                       109                     3,334
3                                        94                     3,798
4                                         6                       383

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                     1,820                    1,265  2019
1                       145                      104  2019
2                     1,965                    1,369  2019
3                     2,537                    1,261  2019
4                       286                       97  2019

[5 rows x 33 columns]
0       2019
1       2019
2       2019
3       2019
4       2019
        ...
3685    2019
3686    2019
3687    2019
3688    2019
3689    2019
Name: Jahr, Length: 3690, dtype: int64

In [13]:
df_2020=pd.read_csv("Opfer_2020.csv",encoding='ISO-8859-1', sep=';')
df_2020.columns = df_2020.columns.str.replace(' ', '')
df_2020["Jahr"] = 2020
print(df_2020.head())
print(df_2020["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

  Operinsgesamt Opfermaennlich Opferweiblich  \
0         3,981          2,335         1,646
1           282            168           114
2         4,263          2,503         1,760
3         4,541          2,874         1,667
4           462            327           135

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                    40                                    22
1                                     2                                     2
2                                    42                                    24
3                                    44                                    19
4                                     2                                     0

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                       2,973
1  ...                                         205
2  ...                                       3,178
3  ...                                       3,303
4  ...                                         340

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                      1,763
1                                        129
2                                      1,892
3                                      2,163
4                                        238

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                     1,210
1                                        76
2                                     1,286
3                                     1,140
4                                       102

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                        270
1                                         37
2                                        307
3                                        236
4                                         31

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                        163
1                                         17
2                                        180
3                                        136
4                                         20

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                       107                     3,243
1                                        20                       242
2                                       127                     3,485
3                                       100                     3,539
4                                        11                       371

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                     1,926                    1,317  2020
1                       146                       96  2020
2                     2,072                    1,413  2020
3                     2,299                    1,240  2020
4                       258                      113  2020

[5 rows x 33 columns]
0       2020
1       2020
2       2020
3       2020
4       2020
        ...
3685    2020
3686    2020
3687    2020
3688    2020
3689    2020
Name: Jahr, Length: 3690, dtype: int64

In [14]:
df_2021=pd.read_csv("Opfer_2021.csv",encoding='ISO-8859-1', sep=';')
df_2021.columns = df_2021.columns.str.replace(' ', '')
df_2021["Jahr"] = 2021
print(df_2021.head())
print(df_2021["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      voll.
1     ------  Straftaten insgesamt             5334002    Aachen      vers.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      voll.
4     ------  Straftaten insgesamt             9761000  Augsburg      vers.

  Operinsgesamt Opfermaennlich Opferweiblich  \
0         3,952          2,304         1,648
1           345            203           142
2         4,297          2,507         1,790
3         4,142          2,565         1,577
4           477            336           141

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                    19                                     8
1                                     2                                     1
2                                    21                                     9
3                                    48                                    26
4                                     1                                     0

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                       2,970
1  ...                                         249
2  ...                                       3,219
3  ...                                       3,066
4  ...                                         376

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                      1,748
1                                        156
2                                      1,904
3                                      1,968
4                                        278

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                     1,222
1                                        93
2                                     1,315
3                                     1,098
4                                        98

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                        280
1                                         49
2                                        329
3                                        239
4                                         23

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                        187
1                                         23
2                                        210
3                                        112
4                                         11

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                        93                     3,250
1                                        26                       298
2                                       119                     3,548
3                                       127                     3,305
4                                        12                       399

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                     1,935                    1,315  2021
1                       179                      119  2021
2                     2,114                    1,434  2021
3                     2,080                    1,225  2021
4                       289                      110  2021

[5 rows x 33 columns]
0       2021
1       2021
2       2021
3       2021
4       2021
        ...
3730    2021
3731    2021
3732    2021
3733    2021
3734    2021
Name: Jahr, Length: 3735, dtype: int64

In [15]:
df_2022=pd.read_csv("Opfer_2022.csv",encoding='ISO-8859-1', sep=';')
df_2022.columns = df_2022.columns.str.replace(' ', '')
df_2022["Jahr"] = 2022
print(df_2022.head())
print(df_2022["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      vers.
1     ------  Straftaten insgesamt             5334002    Aachen      voll.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      vers.
4     ------  Straftaten insgesamt             9761000  Augsburg      voll.

  Operinsgesamt Opfermaennlich Opferweiblich  \
0           399            256           143
1         4,561          2,659         1,902
2         4,960          2,915         2,045
3           505            333           172
4         5,100          3,221         1,879

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                     7                                     6
1                                    36                                    19
2                                    43                                    25
3                                    10                                     9
4                                    56                                    39

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                         288
1  ...                                       3,312
2  ...                                       3,600
3  ...                                         364
4  ...                                       3,661

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                        182
1                                      1,982
2                                      2,164
3                                        250
4                                      2,343

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                       106
1                                     1,330
2                                     1,436
3                                       114
4                                     1,318

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                         38
1                                        344
2                                        382
3                                         25
4                                        273

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                         22
1                                        199
2                                        221
3                                         15
4                                        154

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                        16                       326
1                                       145                     3,656
2                                       161                     3,982
3                                        10                       389
4                                       119                     3,934

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                       204                      122  2022
1                     2,181                    1,475  2022
2                     2,385                    1,597  2022
3                       265                      124  2022
4                     2,497                    1,437  2022

[5 rows x 33 columns]
0       2022
1       2022
2       2022
3       2022
4       2022
        ...
3775    2022
3776    2022
3777    2022
3778    2022
3779    2022
Name: Jahr, Length: 3780, dtype: int64

In [16]:
df_2023=pd.read_csv("Opfer_2023.csv",encoding='ISO-8859-1', sep=';')
df_2023.columns = df_2023.columns.str.replace(' ', '')
df_2023["Jahr"] = 2023
print(df_2023.head())
print(df_2023["Jahr"])

  Schluessel              Straftat  Gemeindeschluessel     Stadt Fallstatus  \
0     ------  Straftaten insgesamt             5334002    Aachen      vers.
1     ------  Straftaten insgesamt             5334002    Aachen      voll.
2     ------  Straftaten insgesamt             5334002    Aachen      insg.
3     ------  Straftaten insgesamt             9761000  Augsburg      vers.
4     ------  Straftaten insgesamt             9761000  Augsburg      voll.

  Operinsgesamt Opfermaennlich Opferweiblich  \
0           436            278           158
1         4,595          2,777         1,818
2         5,031          3,055         1,976
3           561            364           197
4         5,654          3,480         2,174

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                     3                                     1
1                                    30                                    17
2                                    33                                    18
3                                     3                                     3
4                                    52                                    32

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                         334
1  ...                                       3,378
2  ...                                       3,712
3  ...                                         402
4  ...                                       3,979

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                        215
1                                      2,063
2                                      2,278
3                                        263
4                                      2,518

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                       119
1                                     1,315
2                                     1,434
3                                       139
4                                     1,461

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                         41
1                                        340
2                                        381
3                                         46
4                                        336

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                         25
1                                        218
2                                        243
3                                         22
4                                        185

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                        16                       375
1                                       122                     3,718
2                                       138                     4,093
3                                        24                       448
4                                       151                     4,315

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                       240                      135  2023
1                     2,281                    1,437  2023
2                     2,521                    1,572  2023
3                       285                      163  2023
4                     2,703                    1,612  2023

[5 rows x 33 columns]
0       2023
1       2023
2       2023
3       2023
4       2023
        ...
3730    2023
3731    2023
3732    2023
3733    2023
3734    2023
Name: Jahr, Length: 3735, dtype: int64

In [23]:

df_combine=pd.concat([df_2014,df_2015,df_2016,df_2017,df_2018],ignore_index=True)
df_combine.to_csv("df.combine.csv",index=False)
print(df_combine.head(10))
print(df_combine.tail(10))

  SchluesselzahlderTat              Straftat  Gemeindeschlüssel  \
0               ------  Straftaten insgesamt          5334002.0
1               ------  Straftaten insgesamt          5334002.0
2               ------  Straftaten insgesamt          5334002.0
3               ------  Straftaten insgesamt          9761000.0
4               ------  Straftaten insgesamt          9761000.0
5               ------  Straftaten insgesamt          9761000.0
6               ------  Straftaten insgesamt          5378004.0
7               ------  Straftaten insgesamt          5378004.0
8               ------  Straftaten insgesamt          5378004.0
9               ------  Straftaten insgesamt         11000000.0

               Stadt Fallstatus Opferinsgesamt-Anzahl  \
0             Aachen      voll.                  4033
1             Aachen      vers.                   327
2             Aachen      insg.                  4360
3           Augsburg      voll.                  4599
4           Augsburg      vers.                   544
5           Augsburg      insg.                  5143
6  Bergisch Gladbach      voll.                   986
7  Bergisch Gladbach      vers.                    68
8  Bergisch Gladbach      insg.                  1054
9             Berlin      voll.                 70048

   Opferinsgesamtmännlich-Anzahl Opferinsgesamtweiblich-Anzahl  \
0                         2377.0                          1656
1                          206.0                           121
2                         2583.0                          1777
3                         2940.0                          1659
4                          410.0                           134
5                         3350.0                          1793
6                          510.0                           476
7                           44.0                            24
8                          554.0                           500
9                        42392.0                         27656

   Kinderbisunter6Jahre-Anzahl  Kinderbisunter6Jahremännlich-Anzahl  ...  \
0                           15                                  6.0  ...
1                            3                                  0.0  ...
2                           18                                  6.0  ...
3                           30                                 21.0  ...
4                            3                                  1.0  ...
5                           33                                 22.0  ...
6                            8                                  3.0  ...
7                            0                                  0.0  ...
8                            8                                  3.0  ...
9                          774                                408.0  ...

   Erwachsene21bisunter23Jahremaennlich-Anzahl  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
5                                          NaN
6                                          NaN
7                                          NaN
8                                          NaN
9                                          NaN

   Erwachsene23bisunter25Jahremaennlich-Anzahl  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
5                                          NaN
6                                          NaN
7                                          NaN
8                                          NaN
9                                          NaN

   Erwachsene21bisunter25Jahre-maennlich  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
6                                    NaN
7                                    NaN
8                                    NaN
9                                    NaN

   Erwachsene25bisunter30Jahre-maennlich  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
6                                    NaN
7                                    NaN
8                                    NaN
9                                    NaN

   Erwachsene30bisunter40Jahre-maennlich  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
6                                    NaN
7                                    NaN
8                                    NaN
9                                    NaN

   Erwachsene40bisunter50Jahre-maennlich  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
6                                    NaN
7                                    NaN
8                                    NaN
9                                    NaN

   Erwachsene50bisunter60Jahre-maennlich Erwachsene60Jahreundaelter-maennlich  \
0                                    NaN                                  NaN
1                                    NaN                                  NaN
2                                    NaN                                  NaN
3                                    NaN                                  NaN
4                                    NaN                                  NaN
5                                    NaN                                  NaN
6                                    NaN                                  NaN
7                                    NaN                                  NaN
8                                    NaN                                  NaN
9                                    NaN                                  NaN

   Erwachseneab21Jahre-maennlich  Unnamed:68
0                            NaN         NaN
1                            NaN         NaN
2                            NaN         NaN
3                            NaN         NaN
4                            NaN         NaN
5                            NaN         NaN
6                            NaN         NaN
7                            NaN         NaN
8                            NaN         NaN
9                            NaN         NaN

[10 rows x 93 columns]
      SchluesselzahlderTat                                  Straftat  \
55376                  NaN  Mord, Totschlag und T tung auf Verlangen
55377                  NaN  Mord, Totschlag und T tung auf Verlangen
55378                  NaN  Mord, Totschlag und T tung auf Verlangen
55379                  NaN  Mord, Totschlag und T tung auf Verlangen
55380                  NaN  Mord, Totschlag und T tung auf Verlangen
55381                  NaN  Mord, Totschlag und T tung auf Verlangen
55382                  NaN  Mord, Totschlag und T tung auf Verlangen
55383                  NaN  Mord, Totschlag und T tung auf Verlangen
55384                  NaN  Mord, Totschlag und T tung auf Verlangen
55385                  NaN  Mord, Totschlag und T tung auf Verlangen

       Gemeindeschlüssel      Stadt Fallstatus Opferinsgesamt-Anzahl  \
55376                NaN   Schwerin      insg.                     2
55377                NaN     Siegen      insg.                     1
55378                NaN   Solingen      insg.                     3
55379                NaN  Stuttgart      insg.                    46
55380                NaN      Trier      insg.                     1
55381                NaN        Ulm      insg.                    19
55382                NaN  Wiesbaden      insg.                    11
55383                NaN  Wolfsburg      insg.                     4
55384                NaN  Wuppertal      insg.                    17
55385                NaN   W rzburg      insg.                    12

       Opferinsgesamtmännlich-Anzahl Opferinsgesamtweiblich-Anzahl  \
55376                            NaN                             2
55377                            NaN                             1
55378                            NaN                             2
55379                            NaN                            12
55380                            NaN                             1
55381                            NaN                             8
55382                            NaN                             3
55383                            NaN                             2
55384                            NaN                             7
55385                            NaN                             1

       Kinderbisunter6Jahre-Anzahl  Kinderbisunter6Jahremännlich-Anzahl  ...  \
55376                            0                                  NaN  ...
55377                            0                                  NaN  ...
55378                            1                                  NaN  ...
55379                            3                                  NaN  ...
55380                            0                                  NaN  ...
55381                            2                                  NaN  ...
55382                            0                                  NaN  ...
55383                            0                                  NaN  ...
55384                            2                                  NaN  ...
55385                            0                                  NaN  ...

       Erwachsene21bisunter23Jahremaennlich-Anzahl  \
55376                                            0
55377                                            0
55378                                            0
55379                                            2
55380                                            0
55381                                            1
55382                                            0
55383                                            0
55384                                            1
55385                                            1

       Erwachsene23bisunter25Jahremaennlich-Anzahl  \
55376                                            0
55377                                            0
55378                                            0
55379                                            4
55380                                            0
55381                                            0
55382                                            1
55383                                            1
55384                                            0
55385                                            0

       Erwachsene21bisunter25Jahre-maennlich  \
55376                                      0
55377                                      0
55378                                      0
55379                                      6
55380                                      0
55381                                      1
55382                                      1
55383                                      1
55384                                      1
55385                                      1

       Erwachsene25bisunter30Jahre-maennlich  \
55376                                      0
55377                                      0
55378                                      0
55379                                      6
55380                                      0
55381                                      0
55382                                      2
55383                                      0
55384                                      1
55385                                      4

       Erwachsene30bisunter40Jahre-maennlich  \
55376                                      0
55377                                      0
55378                                      1
55379                                      8
55380                                      0
55381                                      1
55382                                      1
55383                                      1
55384                                      3
55385                                      3

       Erwachsene40bisunter50Jahre-maennlich  \
55376                                      0
55377                                      0
55378                                      0
55379                                      8
55380                                      0
55381                                      0
55382                                      0
55383                                      0
55384                                      2
55385                                      0

       Erwachsene50bisunter60Jahre-maennlich  \
55376                                      0
55377                                      0
55378                                      0
55379                                      1
55380                                      0
55381                                      2
55382                                      1
55383                                      0
55384                                      0
55385                                      1

      Erwachsene60Jahreundaelter-maennlich  Erwachseneab21Jahre-maennlich  \
55376                                    0                              0
55377                                    0                              0
55378                                    0                              1
55379                                    2                             31
55380                                    0                              0
55381                                    4                              8
55382                                    0                              5
55383                                    0                              2
55384                                    1                              8
55385                                    0                              9

       Unnamed:68
55376         NaN
55377         NaN
55378         NaN
55379         NaN
55380         NaN
55381         NaN
55382         NaN
55383         NaN
55384         NaN
55385         NaN

[10 rows x 93 columns]

In [18]:
print(df_combine.columns)

Index(['SchluesselzahlderTat', 'Straftat', 'Gemeindeschlüssel', 'Stadt',
       'Fallstatus', 'Opferinsgesamt-Anzahl', 'Opferinsgesamtmännlich-Anzahl',
       'Opferinsgesamtweiblich-Anzahl', 'Kinderbisunter6Jahre-Anzahl',
       'Kinderbisunter6Jahremännlich-Anzahl',
       'Kinderbisunter6Jahreweiblich-Anzahl', 'Kinder6bisunter8JahreAnzahl',
       'Kinder6bisunter8Jahremännlich-Anzahl',
       'Kinder6bisunter8Jahreweiblich-Anzahl', 'Kinder8bisunter10Jahre-Anzahl',
       'Kinder8bisunter10Jahremännlich-Anzahl',
       'Kinder8bisunter10Jahreweiblich-Anzahl',
       'Kinder10bisunter12Jahre-Anzahl',
       'Kinder10bisunter12Jahremännlich-Anzahl',
       'Kinder10bisunter12Jahreweiblich-Anzahl',
       'Kinder12bisunter14Jahre-Anzahl',
       'Kinder12bisunter14Jahremännlich-Anzahl',
       'Kinder12bisunter14Jahreweiblich-Anzahl',
       'Kinderbisunter14Jahreinsgesamt',
       'Kinderbisunter14Jahreinsgesamtmännlich',
       'Kinderbisunter14Jahreinsgesamtweiblich',
       'Jugendliche14bisunter16Jahre-Anzahl',
       'Jugendliche14bisunter16Jahremännlich-Anzahl',
       'Jugendliche14bisunter16Jahreweiblich-Anzahl',
       'Jugendliche16bisunter18Jahre-Anzahl',
       'Jugendliche16bisunter18Jahremännlich-Anzahl',
       'Jugendliche16bisunter18Jahreweiblich-Anzahl',
       'Jugendliche14bisunter18Jahreinsgesamt',
       'Jugendliche14bisunter18Jahreinsgesamt-männlich',
       'Jugendliche14bisunter18Jahreinsgesamt-weiblich',
       'Heranwachsende18bisunter21Jahre-Anzahl',
       'Heranwachsende18bisunter21Jahremännlich-Anzahl',
       'Heranwachsende18bisunter21Jahreweiblich-Anzahl',
       'Opferinsgesamtunter21Jahre', 'Opferinsgesamtunter21Jahre-männlich',
       'Opferinsgesamtunter21Jahre-weiblich',
       'Erwachsene21bisunter23Jahre-Anzahl',
       'Erwachsene21bisunter23Jahremännlich-Anzahl',
       'Erwachsene21bisunter23Jahreweiblich-Anzahl',
       'Erwachsene23bisunter25Jahre-Anzahl',
       'Erwachsene23bisunter25Jahremännlich-Anzahl',
       'Erwachsene23bisunter25Jahreweiblich-Anzahl',
       'Erwachsene21bisunter25Jahre', 'Erwachsene21bisunter25Jahre-männlich',
       'Erwachsene21bisunter25Jahre-weiblich', 'Erwachsene25bisunter30Jahre',
       'Erwachsene25bisunter30Jahre-männlich',
       'Erwachsene25bisunter30Jahre-weiblich', 'Erwachsene30bisunter40Jahre',
       'Erwachsene30bisunter40Jahre-männlich',
       'Erwachsene30bisunter40Jahre-weiblich', 'Erwachsene40bisunter50Jahre',
       'Erwachsene40bisunter50Jahre-männlich',
       'Erwachsene40bisunter50Jahre-weiblich', 'Erwachsene50bisunter60Jahre',
       'Erwachsene50bisunter60Jahre-männlich',
       'Erwachsene50bisunter60Jahre-weiblich', 'Erwachsene60Jahreundaelter',
       'Erwachsene60Jahreundaelter-männlich',
       'Erwachsene60Jahreundaelter-weiblich', 'Erwachseneab21Jahre',
       'Erwachseneab21Jahre-männlich', 'Erwachseneab21Jahre-weiblich', 'Jahr',
       'Schluessel', 'Gemeindeschluessel', 'Opferinsgesamtmaennlich-Anzahl',
       'Kinderbisunter6Jahremaennlich-Anzahl',
       'Kinder6bisunter8Jahremaennlich-Anzahl',
       'Kinder8bisunter10Jahremaennlich-Anzahl',
       'Kinder10bisunter12Jahremaennlich-Anzahl',
       'Kinder12bisunter14Jahremaennlich-Anzahl',
       'Kinderbisunter14Jahreinsgesamtmaennlich',
       'Jugendliche14bisunter16Jahremaennlich-Anzahl',
       'Jugendliche16bisunter18Jahremaennlich-Anzahl',
       'Jugendliche14bisunter18Jahreinsgesamt-maennlich',
       'Heranwachsende18bisunter21Jahremaennlich-Anzahl',
       'Opferinsgesamtunter21Jahre-maennlich',
       'Erwachsene21bisunter23Jahremaennlich-Anzahl',
       'Erwachsene23bisunter25Jahremaennlich-Anzahl',
       'Erwachsene21bisunter25Jahre-maennlich',
       'Erwachsene25bisunter30Jahre-maennlich',
       'Erwachsene30bisunter40Jahre-maennlich',
       'Erwachsene40bisunter50Jahre-maennlich',
       'Erwachsene50bisunter60Jahre-maennlich',
       'Erwachsene60Jahreundaelter-maennlich', 'Erwachseneab21Jahre-maennlich',
       'Unnamed:68'],
      dtype='object')

In [25]:
df_combined=pd.concat([df_2019,df_2020,df_2021,df_2022,df_2023],ignore_index=True)
df_combined.to_csv("df.combined.csv",index=False)
print(df_combined.head(10))
print(df_combined.tail(10))

  Schluessel              Straftat  Gemeindeschluessel              Stadt  \
0     ------  Straftaten insgesamt             5334002             Aachen
1     ------  Straftaten insgesamt             5334002             Aachen
2     ------  Straftaten insgesamt             5334002             Aachen
3     ------  Straftaten insgesamt             9761000           Augsburg
4     ------  Straftaten insgesamt             9761000           Augsburg
5     ------  Straftaten insgesamt             9761000           Augsburg
6     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
7     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
8     ------  Straftaten insgesamt             5378004  Bergisch Gladbach
9     ------  Straftaten insgesamt            11000000             Berlin

  Fallstatus Operinsgesamt Opfermaennlich Opferweiblich  \
0      voll.         3,828          2,252         1,576
1      vers.           304            182           122
2      insg.         4,132          2,434         1,698
3      voll.         4,879          3,198         1,681
4      vers.           480            354           126
5      insg.         5,359          3,552         1,807
6      voll.         1,136            606           530
7      vers.            70             40            30
8      insg.         1,206            646           560
9      voll.        75,836         46,380        29,456

   Opfer-Kinderbisunter6Jahre-insgesamt  Opfer-Kinderbisunter6Jahre-maennlich  \
0                                    23                                    13
1                                     1                                     0
2                                    24                                    13
3                                    26                                    17
4                                     4                                     2
5                                    30                                    19
6                                     9                                     3
7                                     1                                     1
8                                    10                                     4
9                                   792                                   435

   ...  OpferErwachsene21bisunter60Jahre-insgesamt  \
0  ...                                       2,809
1  ...                                         234
2  ...                                       3,043
3  ...                                       3,555
4  ...                                         368
5  ...                                       3,923
6  ...                                         781
7  ...                                          53
8  ...                                         834
9  ...                                      55,866

  OpferErwachsene21bisunter60Jahre-maennlich  \
0                                      1,645
1                                        138
2                                      1,783
3                                      2,388
4                                        277
5                                      2,665
6                                        420
7                                         28
8                                        448
9                                     34,859

  OpferErwachsene21bisunter60Jahre-weiblich  \
0                                     1,164
1                                        96
2                                     1,260
3                                     1,167
4                                        91
5                                     1,258
6                                       361
7                                        25
8                                       386
9                                    21,007

  Opfer-Erwachsene60Jahreundaelter-insgesamt  \
0                                        276
1                                         15
2                                        291
3                                        243
4                                         15
5                                        258
6                                        106
7                                          4
8                                        110
9                                      4,436

  Opfer-Erwachsene60Jahreundaelter-maennlich  \
0                                        175
1                                          7
2                                        182
3                                        149
4                                          9
5                                        158
6                                         53
7                                          2
8                                         55
9                                      2,409

  Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
0                                       101                     3,085
1                                         8                       249
2                                       109                     3,334
3                                        94                     3,798
4                                         6                       383
5                                       100                     4,181
6                                        53                       887
7                                         2                        57
8                                        55                       944
9                                     2,027                    60,302

  OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
0                     1,820                    1,265  2019
1                       145                      104  2019
2                     1,965                    1,369  2019
3                     2,537                    1,261  2019
4                       286                       97  2019
5                     2,823                    1,358  2019
6                       473                      414  2019
7                        30                       27  2019
8                       503                      441  2019
9                    37,268                   23,034  2019

[10 rows x 33 columns]
      Schluessel                                  Straftat  \
18620     892500  Mord, Totschlag und T tung auf Verlangen
18621     892500  Mord, Totschlag und T tung auf Verlangen
18622     892500  Mord, Totschlag und T tung auf Verlangen
18623     892500  Mord, Totschlag und T tung auf Verlangen
18624     892500  Mord, Totschlag und T tung auf Verlangen
18625     892500  Mord, Totschlag und T tung auf Verlangen
18626     892500  Mord, Totschlag und T tung auf Verlangen
18627     892500  Mord, Totschlag und T tung auf Verlangen
18628     892500  Mord, Totschlag und T tung auf Verlangen
18629     892500  Mord, Totschlag und T tung auf Verlangen

       Gemeindeschluessel      Stadt Fallstatus Operinsgesamt Opfermaennlich  \
18620             6414000  Wiesbaden      insg.            21             11
18621             3103000  Wolfsburg      vers.             3              2
18622             3103000  Wolfsburg      voll.             0              0
18623             3103000  Wolfsburg      insg.             3              2
18624             5124000  Wuppertal      vers.             5              3
18625             5124000  Wuppertal      voll.             1              1
18626             5124000  Wuppertal      insg.             6              4
18627             9663000   W rzburg      vers.             4              4
18628             9663000   W rzburg      voll.             0              0
18629             9663000   W rzburg      insg.             4              4

      Opferweiblich  Opfer-Kinderbisunter6Jahre-insgesamt  \
18620            10                                     0
18621             1                                     0
18622             0                                     0
18623             1                                     0
18624             2                                     0
18625             0                                     0
18626             2                                     0
18627             0                                     0
18628             0                                     0
18629             0                                     0

       Opfer-Kinderbisunter6Jahre-maennlich  ...  \
18620                                     0  ...
18621                                     0  ...
18622                                     0  ...
18623                                     0  ...
18624                                     0  ...
18625                                     0  ...
18626                                     0  ...
18627                                     0  ...
18628                                     0  ...
18629                                     0  ...

       OpferErwachsene21bisunter60Jahre-insgesamt  \
18620                                          18
18621                                           1
18622                                           0
18623                                           1
18624                                           4
18625                                           1
18626                                           5
18627                                           4
18628                                           0
18629                                           4

      OpferErwachsene21bisunter60Jahre-maennlich  \
18620                                         11
18621                                          1
18622                                          0
18623                                          1
18624                                          2
18625                                          1
18626                                          3
18627                                          4
18628                                          0
18629                                          4

      OpferErwachsene21bisunter60Jahre-weiblich  \
18620                                         7
18621                                         0
18622                                         0
18623                                         0
18624                                         2
18625                                         0
18626                                         2
18627                                         0
18628                                         0
18629                                         0

      Opfer-Erwachsene60Jahreundaelter-insgesamt  \
18620                                          3
18621                                          0
18622                                          0
18623                                          0
18624                                          1
18625                                          0
18626                                          1
18627                                          0
18628                                          0
18629                                          0

      Opfer-Erwachsene60Jahreundaelter-maennlich  \
18620                                          0
18621                                          0
18622                                          0
18623                                          0
18624                                          1
18625                                          0
18626                                          1
18627                                          0
18628                                          0
18629                                          0

      Opfer-Erwachsene60Jahreundaelter-weiblich OpferErwachsene-insgesamt  \
18620                                         3                        21
18621                                         0                         1
18622                                         0                         0
18623                                         0                         1
18624                                         0                         5
18625                                         0                         1
18626                                         0                         6
18627                                         0                         4
18628                                         0                         0
18629                                         0                         4

      OpferErwachsene-maennlich OpferErwachsene-weiblich  Jahr
18620                        11                       10  2023
18621                         1                        0  2023
18622                         0                        0  2023
18623                         1                        0  2023
18624                         3                        2  2023
18625                         1                        0  2023
18626                         4                        2  2023
18627                         4                        0  2023
18628                         0                        0  2023
18629                         4                        0  2023

[10 rows x 33 columns]

In [26]:
 # The number of columns is the second element in the shape tuple
print(f"Number of columns: {df_2014.shape[1]}")
print(f"Number of columns: {df_2015.shape[1]}")
print(f"Number of columns: {df_2016.shape[1]}")
print(f"Number of columns: {df_2017.shape[1]}")
print(f"Number of columns: {df_2018.shape[1]}")

Number of columns: 69
Number of columns: 69
Number of columns: 69
Number of columns: 69
Number of columns: 69

In [ ]:
#rename columns